[package]
name = "btm"
version = "0.1.4"
edition = "2018"

keywords = ["version-control", "blockchain", "zfs", "btrfs"]

license = "MIT"
authors = ["FindoraNetwork"]
description = "Blockchain Time Machine"
homepage = "https://github.com/FindoraNetwork/btm"
repository = "https://github.com/FindoraNetwork/btm.git"

[dependencies]
ruc = { version = "0.6.5", features = ["rich"]}
clap = "2.33.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.40"
lazy_static = "1.4.0"

[[bin]]
name = "btm"
path = "src/bins/btm.rs"
