[package]
name = "btm"
version = "0.1.7"
edition = "2021"
keywords = ["version-control", "snapshot", "zfs", "btrfs"]
license = "MIT"
authors = ["fanhui.x@gmail.com"]
description = "Blockchain Time Machine"
homepage = "https://github.com/ccmlm/btm"
repository = "https://github.com/ccmlm/btm.git"

[dependencies]
ruc = { version = "0.6.5", features = ["rich"]}
clap = "2.33.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.40"
lazy_static = "1.4.0"
nix = "0.22.2"

[[bin]]
name = "btm"
path = "src/bins/btm.rs"
